FROM python:3.6-slim
COPY requirements.txt requirements.txt
RUN pip install virtualenv && virtualenv venv && . venv/bin/activate && pip install prospector && pip install mypy && pip install -r requirements.txt
ENV PATH /venv/bin:$PATH