version: '2.2'
services:
  watchdog:
    image: docker-container-watchdog:latest
    mem_limit: 50m
    cpus: 1
    environment:
      - DOCKER_HOSTMACHINE=${HOSTNAME}
#      - POLLING_INTERVAL=30
#      - POLLING_INTERVAL_AFTER_RESTART=600
#      - SLACK_WEBHOOK_URL=
#      - SMTP_SERVER=
#      - EMAIL_RECEIVER=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    security_opt:
     - label:disable